@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

title Component diagram illustrating how lantern-water integration works

Component(versionControl, "Version control Manager", "go", "Allow the client to manage WASM files available locally. If the WASM file isn't available locally and was never loaded it'll try to download the file and load the file in memory. If the WASM file isn't used in the period of 7 days, it'll be deleted")
Component(downloader, "Downloader", "go", "Provide ways to download WASM files from given URLs. Currently it supports HTTPS URLs and magnet links.")
Component(dialer, "Dialer", "go, water", "The dialer initializes a water dialer with the given WASM bytes and parameters.")
Component(clientApp, "Client app", "go", "The example client app use the packages available to download and run a water dialer")

Rel(clientApp, versionControl, "Request WASM")
Rel(versionControl, downloader, "If WASM isn't available locally, try to download it")
Rel(clientApp, dialer, "When WASM is available in memory, initialize dialer")

Component(downloader, "Downloader", "go", "Provide ways to download WASM files from given URLs. Currently it supports HTTPS URLs and magnet links.")
Component(listener, "Listener", "go, water", "The dialer initializes a water dialer with the given WASM bytes and parameters.")
Component(listenerApp, "Listener app", "go", "The example listener app use the packages available to download and run a water listener")

Rel(listenerApp, downloader, "Request WASM")
Rel(listenerApp, listener, "Initialize listener when WASM is available in memory")

Rel(clientApp, listenerApp,  "Send/receive request", "Water WASM")

@enduml
